[2021/11/30 09:23:16]========== Start ==========
[2021/11/30 09:23:16][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:23:16][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:23:16][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:23:16][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:23:22][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:23:22][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:23:22][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:23:22][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:23:23][I][pullData] ----- Pulling Data ------
[2021/11/30 09:23:23][E][pullData] Unexpected error: [WinError 3] 系統找不到指定的路徑。: '/home/sanchez/Desktop/RDTool/Automation_RSSI_WiFiSARQUERY/ARW_temp/78329'
[2021/11/30 09:23:23][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:23:23][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:23:23][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:23:23][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:23:23][E][log_to_excel] Unexpected Error: list index out of range
[2021/11/30 09:23:23][I][main] Spend Time: 6 s
[2021/11/30 09:23:44][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200C97080B8>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:23:44]========== End ==========
[2021/11/30 09:26:18]========== Start ==========
[2021/11/30 09:26:18][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:26:18][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:26:18][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:26:18][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:26:23][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:26:23][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:26:23][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:26:23][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:26:23][I][pullData] ----- Pulling Data ------
[2021/11/30 09:26:23][E][pullData] Unexpected error: local variable 'n_fcount' referenced before assignment
[2021/11/30 09:26:23][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:26:23][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:26:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:26:23][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:26:23][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:26:23][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:26:23][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:26:23][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:26:23][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:26:23][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:26:23][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:26:23][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:26:23][I][main] Spend Time: 5 s
[2021/11/30 09:26:44][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B77BAD908>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:26:44]========== End ==========
[2021/11/30 09:26:57]========== Start ==========
[2021/11/30 09:26:57][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:26:57][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:26:57][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:26:57][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:27:02][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:27:02][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:27:02][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:27:02][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:27:02][I][pullData] ----- Pulling Data ------
[2021/11/30 09:27:14][I][pullData] ----- Pulling Data Successfully -----
[2021/11/30 09:27:14][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:27:14][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:27:14][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:27:14][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:27:14][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:27:14][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:27:14][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:27:14][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:27:14][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:27:14][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:27:14][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:27:14][I][main] Spend Time: 16 s
[2021/11/30 09:27:35][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273FF8A31D0>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:27:35]========== End ==========
[2021/11/30 09:29:23]========== Start ==========
[2021/11/30 09:29:23][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:29:23][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:29:23][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:29:23][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:29:29][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:29:29][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:29:29][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:29:29][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:29:29][I][pullData] ----- Pulling Data ------
[2021/11/30 09:29:41][I][pullData] ----- Pulling Data Successfully -----
[2021/11/30 09:29:41][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:29:41][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:29:41][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:29:41][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:29:41][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:29:42][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:29:42][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:29:42][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:29:42][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:29:42][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:29:42][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:29:42][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:29:42][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:29:42][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:29:42][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:29:42][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:29:42][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:29:42][I][main] Spend Time: 18 s
[2021/11/30 09:30:03][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019F3EFF02E8>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:30:03]========== End ==========
[2021/11/30 09:31:24]========== Start ==========
[2021/11/30 09:31:24][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:31:24][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:31:24][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:31:24][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:31:29][E][initPaht] Unexpected Error: [WinError 32] 程序無法存取檔案，因為檔案正由另一個程序使用。: './input/WillyWJ_Chen\\7224908800007\\DreamColorLog\\_20220101141625\\CND140BB8B_20220101135601.log'
[2021/11/30 09:31:29][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:31:29][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:31:29][I][pullData] ----- Pulling Data ------
[2021/11/30 09:31:30][E][pullData] Unexpected error: [WinError 183] 當檔案已存在時，無法建立該檔案。: './input/WillyWJ_Chen\\7224908800007'
[2021/11/30 09:31:30][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:31:30][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:31:30][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:31:30][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:31:30][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:31:30][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:31:30][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:31:30][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:31:30][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:31:30][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:31:30][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:31:30][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:31:30][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:31:30][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:31:30][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:31:30][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:31:30][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:31:30][I][main] Spend Time: 6 s
[2021/11/30 09:31:51][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000130AA3A0320>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:31:51]========== End ==========
[2021/11/30 09:33:01]========== Start ==========
[2021/11/30 09:33:01][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:33:01][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:33:01][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:33:01][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:33:08][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:33:08][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:33:08][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:33:08][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:33:08][I][pullData] ----- Pulling Data ------
[2021/11/30 09:33:19][I][pullData] ----- Pulling Data Successfully -----
[2021/11/30 09:33:19][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:33:19][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:33:19][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:33:19][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:33:19][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:33:19][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:33:19][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:33:19][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:33:20][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:33:20][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:33:20][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:33:20][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:33:20][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:33:20][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:33:20][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:33:20][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:33:20][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:33:20][I][main] Spend Time: 18 s
[2021/11/30 09:33:41][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002134FE60208>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:33:41]========== End ==========
[2021/11/30 09:45:17]========== Start ==========
[2021/11/30 09:45:17][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:45:17][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:45:17][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:45:17][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:45:22][E][initPaht] Unexpected Error: [WinError 32] 程序無法存取檔案，因為檔案正由另一個程序使用。: './input/WillyWJ_Chen\\7224908800007\\DreamColorLog\\_20220101141625\\CND140BB8B_20220101135601.log'
[2021/11/30 09:45:22][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:45:22][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:45:22][I][pullData] ----- Pulling Data ------
[2021/11/30 09:45:23][E][pullData] Unexpected error: [WinError 183] 當檔案已存在時，無法建立該檔案。: './input/WillyWJ_Chen\\7224908800007'
[2021/11/30 09:45:23][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:45:23][I][start] ------ Begin Generating Sequence -----
[2021/11/30 09:45:23][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:45:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:45:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:45:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:45:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:45:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:45:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:45:23][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:45:23][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:45:23][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:45:23][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:45:23][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:45:23][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:45:23][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:45:23][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:45:23][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:45:23][I][zip_all_files] Compressing files
[2021/11/30 09:45:23][I][start] Saving Zip File to Server
[2021/11/30 09:45:23][I][start] ------ End of Generating Sequence -----
[2021/11/30 09:45:23][I][main] Spend Time: 6 s
[2021/11/30 09:45:44][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002481E600320>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:45:44]========== End ==========
[2021/11/30 09:46:32]========== Start ==========
[2021/11/30 09:46:32][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:46:32][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:46:32][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:46:32][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:46:37][E][initPaht] Unexpected Error: [WinError 32] 程序無法存取檔案，因為檔案正由另一個程序使用。: './input/WillyWJ_Chen\\7228101400001\\TOUCHFW.txt'
[2021/11/30 09:46:37][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:46:37][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:46:37][I][pullData] ----- Pulling Data ------
[2021/11/30 09:46:38][E][pullData] Unexpected error: [WinError 183] 當檔案已存在時，無法建立該檔案。: './input/WillyWJ_Chen\\7228101400001'
[2021/11/30 09:46:38][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:46:38][I][start] ------ Begin Generating Sequence -----
[2021/11/30 09:46:38][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:46:38][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:46:38][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:46:38][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:46:38][W][ParseLog] Cannot find ITPM_RSSITest_A32.LOG and MTKlog_7228101400001.LOG by SN: 7228101400001
[2021/11/30 09:46:38][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228101400001
[2021/11/30 09:46:38][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:46:38][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:46:38][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:46:38][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:46:38][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:46:38][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:46:38][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:46:38][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:46:38][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:46:38][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:46:38][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:46:38][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:46:38][I][zip_all_files] Compressing files
[2021/11/30 09:46:38][I][start] Saving Zip File to Server
[2021/11/30 09:46:38][I][start] ------ End of Generating Sequence -----
[2021/11/30 09:46:38][I][main] Spend Time: 6 s
[2021/11/30 09:46:59][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000224B42963C8>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:46:59]========== End ==========
[2021/11/30 09:47:14]========== Start ==========
[2021/11/30 09:47:14][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:47:14][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:47:14][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:47:14][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:47:21][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:47:21][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:47:21][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:47:21][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:47:21][I][pullData] ----- Pulling Data ------
[2021/11/30 09:47:32][I][pullData] ----- Pulling Data Successfully -----
[2021/11/30 09:47:32][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:47:32][I][start] ------ Begin Generating Sequence -----
[2021/11/30 09:47:32][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:47:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:47:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:47:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:47:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:47:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:47:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:47:32][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:47:32][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:47:32][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:47:32][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:47:32][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:47:32][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:47:32][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:47:32][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:47:32][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:47:32][I][zip_all_files] Compressing files
[2021/11/30 09:47:32][I][start] Saving Zip File to Server
[2021/11/30 09:47:32][I][start] ------ End of Generating Sequence -----
[2021/11/30 09:47:32][I][main] Spend Time: 18 s
[2021/11/30 09:47:53][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CD9C7F0358>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:47:53]========== End ==========
[2021/11/30 09:48:26]========== Start ==========
[2021/11/30 09:48:26][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:48:26][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:48:26][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:48:26]
[I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:48:31][E][initPaht] Unexpected Error: [WinError 32] 程序無法存取檔案，因為檔案正由另一個程序使用。: './input/WillyWJ_Chen\\7228101400001\\VGAThermal.LOG'
[2021/11/30 09:48:31][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:48:31][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:48:31][I][pullData] ----- Pulling Data ------
[2021/11/30 09:48:32][E][pullData] Unexpected error: [WinError 183] 當檔案已存在時，無法建立該檔案。: './input/WillyWJ_Chen\\7228101400001'
[2021/11/30 09:48:32][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:48:32][I][start] ------ Begin Generating Sequence -----

[2021/11/30 09:48:32][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:48:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:48:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:48:32][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:48:32][W][ParseLog] Cannot find ITPM_RSSITest_A32.LOG and MTKlog_7228101400001.LOG by SN: 7228101400001
[2021/11/30 09:48:33][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228101400001
[2021/11/30 09:48:33][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:48:33][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:48:33][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:48:33][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:48:33][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:48:33][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:48:33][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:48:33][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:48:33][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:48:33][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:48:33][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:48:33][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:48:33][I][zip_all_files] Compressing files
[2021/11/30 09:48:33][I][start] Saving Zip File to Server
[2021/11/30 09:48:33][I][start] ------ End of Generating Sequence -----
[2021/11/30 09:48:33][I][main] Spend Time: 6 s
[2021/11/30 09:48:54][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D040C3F2E8>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:48:54]========== End ==========
[2021/11/30 09:48:59]========== Start ==========
[2021/11/30 09:48:59][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:48:59][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:48:59][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:48:59]
[I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:49:06][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:49:06][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:49:06][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:49:06][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:49:06][I][pullData] ----- Pulling Data ------
[2021/11/30 09:49:17][I][pullData] ----- Pulling Data Successfully -----
[2021/11/30 09:49:17][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:49:17][I][start] ------ Begin Generating Sequence -----

[2021/11/30 09:49:17][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:49:17][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:49:17][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:49:17][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:49:17][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:49:17][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:49:17][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:49:17][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:49:17][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:49:17][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:49:17][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:49:17][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:49:17][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:49:17][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:49:17][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:49:17][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:49:17][I][zip_all_files] Compressing files
[2021/11/30 09:49:17][I][start] Saving Zip File to Server
[2021/11/30 09:49:17][I][start] ------ End of Generating Sequence -----
[2021/11/30 09:49:17][I][main] Spend Time: 18 s
[2021/11/30 09:49:38][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000226B6C61390>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:49:38]========== End ==========
[2021/11/30 09:55:26]========== Start ==========
[2021/11/30 09:55:26][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:55:26][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:55:26][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:55:26]
[I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:55:31][E][initPaht] Unexpected Error: [WinError 32] 程序無法存取檔案，因為檔案正由另一個程序使用。: './input/WillyWJ_Chen\\7228101300001\\ITESHC_ColorLog_CalibrationColor.txt'
[2021/11/30 09:55:31][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:55:31][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:55:31][I][pullData] ----- Pulling Data ------
[2021/11/30 09:55:32][E][pullData] Unexpected error: [WinError 183] 當檔案已存在時，無法建立該檔案。: './input/WillyWJ_Chen\\7228101300001'
[2021/11/30 09:55:32][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:55:32][I][start] ------ Begin Generating Sequence -----

[2021/11/30 09:55:33][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:55:33][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:55:33][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:55:33][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:55:34][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:55:34][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:55:34][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:55:34][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:55:35][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:55:35][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:55:35][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:55:35][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:55:35][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:55:35][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:55:35][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:55:35][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:55:36][I][zip_all_files] Compressing files
[2021/11/30 09:55:36][I][start] Saving Zip File to Server
[2021/11/30 09:55:37][I][start] ------ End of Generating Sequence -----
[2021/11/30 09:55:37][I][main] Spend Time: 10 s
[2021/11/30 09:55:58][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025636FE1278>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:55:58]========== End ==========
