[2021/11/30 09:23:16]========== Start ==========
[2021/11/30 09:23:16][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:23:16][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:23:16][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:23:16][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:23:22][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:23:22][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:23:22][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:23:22][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:23:23][I][pullData] ----- Pulling Data ------
[2021/11/30 09:23:23][E][pullData] Unexpected error: [WinError 3] 系統找不到指定的路徑。: '/home/sanchez/Desktop/RDTool/Automation_RSSI_WiFiSARQUERY/ARW_temp/78329'
[2021/11/30 09:23:23][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:23:23][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:23:23][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:23:23][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:23:23][E][log_to_excel] Unexpected Error: list index out of range
[2021/11/30 09:23:23][I][main] Spend Time: 6 s
[2021/11/30 09:23:44][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200C97080B8>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:23:44]========== End ==========
[2021/11/30 09:26:18]========== Start ==========
[2021/11/30 09:26:18][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:26:18][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:26:18][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:26:18][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:26:23][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:26:23][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:26:23][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:26:23][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:26:23][I][pullData] ----- Pulling Data ------
[2021/11/30 09:26:23][E][pullData] Unexpected error: local variable 'n_fcount' referenced before assignment
[2021/11/30 09:26:23][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:26:23][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:26:23][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:26:23][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:26:23][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:26:23][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:26:23][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:26:23][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:26:23][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:26:23][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:26:23][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:26:23][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:26:23][I][main] Spend Time: 5 s
[2021/11/30 09:26:44][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017B77BAD908>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:26:44]========== End ==========
[2021/11/30 09:26:57]========== Start ==========
[2021/11/30 09:26:57][I][main] Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
[2021/11/30 09:26:57][I][main] Automation_RSSI_WiFiSARQUERY.py 1.0.0.1
[2021/11/30 09:26:57][I][main] Decteing User: WillyWJ_Chen

[2021/11/30 09:26:57][I][setPath] ----- Setting Folder Path -----
[2021/11/30 09:27:02][I][initPath] Delete Folder: ./input/WillyWJ_Chen
[2021/11/30 09:27:02][I][initPath] Create Folder: ./input/WillyWJ_Chen
[2021/11/30 09:27:02][I][initPath] Delete Folder: ./output/WillyWJ_Chen
[2021/11/30 09:27:02][I][initPath] Create Folder: ./output/WillyWJ_Chen
[2021/11/30 09:27:02][I][pullData] ----- Pulling Data ------
[2021/11/30 09:27:14][I][pullData] ----- Pulling Data Successfully -----
[2021/11/30 09:27:14][I][setPath] ----- Setting Folder Path Successfully -----
[2021/11/30 09:27:14][I][parseLog] ------- Start Parsing Log -------
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800005
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800006
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7224908800007
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800008
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800009
[2021/11/30 09:27:14][W][ParseLog] Cannot find SarLog_DynAnt.txt by SN: 7228979800010
[2021/11/30 09:27:14][I][parseLog] ------- Finish Parsing Log -------
[2021/11/30 09:27:14][I][log_to_excel] ------- Parsing Log to Excel -------
[2021/11/30 09:27:14][I][log_to_excel] New workbook for RSSI.xlsx
[2021/11/30 09:27:14][I][newSheet] Sheet: RSSI Created
[2021/11/30 09:27:14][I][log_to_excel] RSSI.xlsx generated
[2021/11/30 09:27:14][I][log_to_excel] New workbook for WiFiSARQUERY.xlsx
[2021/11/30 09:27:14][I][newSheet] Sheet: wifisarquery Created
[2021/11/30 09:27:14][I][log_to_excel] WiFiSARQUERY.xlsx generated
[2021/11/30 09:27:14][I][log_to_excel] ------- Parsed Log to Excel -------
[2021/11/30 09:27:14][I][main] Spend Time: 16 s
[2021/11/30 09:27:35][E][main] Unexpected Error: HTTPConnectionPool(host='10.110.140.43', port=80): Max retries exceeded with url: /LYUR/logYourUsageRecord.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273FF8A31D0>: Failed to establish a new connection: [WinError 10060] 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。'))
[2021/11/30 09:27:35]========== End ==========
